#!/bin/zsh
set -euo pipefail

repo_root="${0:A:h:h}"
dist="$repo_root/website/dist"
landing="$dist/index.html"

for file in source/report.md source/report.ru.md source/assets/app-icon.png source/assets/og-image.png \
  source/assets/builder-en.webp source/assets/builder-ru.webp source/assets/shortcuts-en.webp \
  source/assets/shortcuts-ru.webp dist/index.html dist/assets/app-icon.png dist/assets/og-image.png dist/robots.txt dist/sitemap.xml; do
  [[ -s "$repo_root/website/$file" ]] || { print -u2 "Missing landing file: website/$file"; exit 1; }
done

ruby - "$landing" "$dist" <<'RUBY'
html = File.read(ARGV.fetch(0), encoding: "UTF-8")
dist = ARGV.fetch(1)
errors = []
errors << "Landing must be generated by agentic-report" unless html.include?('name="generator" content="agentic-report"')
errors << "Landing must carry both EN and RU variants" unless html.include?('data-package-locale="en"') && html.include?("Одна клавиша запускает весь сценарий")
errors << "Landing contains an insecure external URL" if html.match?(/(?:href|src)="http:\/\//)
runtime_refs = html.scan(/\b(?:src|href)="([^"]+)"/).flatten
html.scan(/<link\b[^>]*>/).each do |tag|
  rel = tag[/\brel="([^"]+)"/, 1].to_s.split
  next if (rel & %w[stylesheet icon preload modulepreload manifest]).empty?

  href = tag[/\bhref="([^"]+)"/, 1]
  errors << "Landing depends on an external runtime asset: #{href}" if href&.start_with?("http")
end
html.scan(/<script\b[^>]*\bsrc="([^"]+)"/).flatten.each do |src|
  errors << "Landing loads an external script: #{src}" if src.start_with?("http")
end
errors << "Landing must not embed inline scripts" if html.match?(/<script\b(?![^>]*\bsrc=)/)
(runtime_refs.grep(/\Aassets\//)).uniq.each do |path|
  errors << "Referenced asset is missing from website/dist: #{path}" unless File.file?(File.join(dist, path))
end
errors << "Download links must point to the latest GitHub release" unless html.include?('href="https://github.com/witqq/mac-utils/releases/latest"')
errors << "The App Store call to action must stay a plain 'coming soon' note until a product URL exists" if html.match?(/href="https:\/\/apps\.apple\.com/)
errors << "Landing must contain the Made with Moira attribution" unless html.match?(/<a\b[^>]*href="https:\/\/moira-mcp\.com\/"[^>]*>(?:(?!<\/a>).)*Made with Moira/m)
social_image = html[%r{property="og:image" content="https://mac-utils\.witqq\.dev/(assets/og-image\.[0-9a-f]{12}\.png)"}, 1]
errors << "Landing must declare its canonical URL and social preview" unless html.include?('rel="canonical" href="https://mac-utils.witqq.dev/"') && social_image && File.file?(File.join(dist, social_image))
errors << "Landing HTML exceeds what search crawlers read" if html.bytesize > 2_097_152
errors << "robots.txt must name the absolute sitemap" unless File.read(File.join(dist, "robots.txt")).include?("Sitemap: https://mac-utils.witqq.dev/sitemap.xml\n")
errors << "sitemap.xml must list the landing" unless File.read(File.join(dist, "sitemap.xml")).include?("<loc>https://mac-utils.witqq.dev/</loc>")
abort errors.join("\n") unless errors.empty?
puts "Landing valid: agentic-report build, EN/RU variants, local runtime assets, HTTPS links, GitHub download, Made with Moira attribution, canonical and social metadata, robots.txt and sitemap.xml."
RUBY
